### ISSUE TITLE
[ENHANCEMENT] Different Highlighting for Command and "statement"

### ISSUE THREAD

**Issue by vabene1111** [kayler-renslow/arma-intellij-plugin#13]
First of all: really love your plugin its great.
Now for my idea:

I have been using Atom for the last few month and there i have different colors for conditions/loops/etc and "commands" like format/localize/etc.
To better understand what i mean see  [this screenshot](https://dl.dropboxusercontent.com/s/quaib6os91e5ujz/2016-07-11_17-09_fn_broadcast.sqf_%E2%80%94_DSteamLibrarySteamAppscommo.png?dl=0)

With your plugin you cant (or at least i could not find the option) make a difference between these two cases and it looks like [this](https://dl.dropboxusercontent.com/s/8ns75bb026d3jsv/2016-07-11_17-11_ReallifeRPG.Abramia_-_%5BDSteamLibrarySteamAppsc.png?dl=0) or whatever color you configure it to.

This is not a big deal, but (and i dont know how much work this would be) it would be great to add an option for that as well.

**Comment by kayler-renslow** [comment]
You can change colors of variables, brackets, etc. but individual commands can't have their own color. All commands can only be one color. That is a limitation to Intellij.

**Comment by kayler-renslow** [comment]
View the Intellij documentation for more: https://www.jetbrains.com/help/idea/2016.1/configuring-colors-and-fonts.html

**Comment by vabene1111** [comment]
Ok thank you, still a great plugin
