### ISSUE TITLE
support for dikCode values like 0x00 and 0x01

### ISSUE THREAD

**Issue by BangL** [kayler-renslow/arma-intellij-plugin#15]
example:  _fKeyPressed =(_dikCode in [0x3F,0x3E,0x3D,0x3C,0x3B,0x44,0x43,0x42,0x41,0x40,0x58,0x57]);

those 0xXX values are valid and should be handled like numbers.

see this: https://community.bistudio.com/wiki/DIK_KeyCodes

**Comment by kayler-renslow** [comment]
this will be fixed in next release.
