### ISSUE TITLE
Objectparent method syntax validation

### ISSUE THREAD

**Issue by tomaytotomato** [kayler-renslow/arma-intellij-plugin#19]
For a code block like this 

```
//check if unit hit is vehicle, if so then exit
if (!isNull objectparent _unitHit) exitWith {};

```

Is throwing a false positive warning for syntax 

> Expected '(',')',':',';' got _variable instead

**Comment by kayler-renslow** [comment]
All commands are required to be camelCase. See https://github.com/kayler-renslow/arma-intellij-plugin/issues/3 for more info.

fix: `if (!isNull objectParent _unitHit) exitWith {};
`
