### ISSUE TITLE
missionNamespace setVariable ... 

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#20]
version 1.0.5 : "there is a syntax error. <Expression>,<comment>,command,Identifier,LANG_VAR,String or '[' expected, got 'missionNamespace'. Error line number .. 
Here is the code that causes the error. 
`
missionNamespace setVariable ["client_fnc_" + _fileName, _function];
`
example 3!
https://community.bistudio.com/wiki/setVariable
this time, i'm not as stupid as the last time!  :D 
cheers

**Comment by kayler-renslow** [comment]
I opened this up in the editor and this doesn't seem to be an issue for me. Can you post the entire file's code?

**Comment by Ragebone** [comment]
it was a missing bracket that i and 3 other people overlooked.
this is a good example. 
The error message is misleading.
`_func = "bla" + ("bla";`
`missionNamespace setVariable["bla",false];`

Side note, noticed how awesom your cfgFunctions automation works. THX for that!

**Comment by kayler-renslow** [comment]
glad to see everything is working as intended. :)
