### ISSUE TITLE
Crash on certain files (With random cpu usage pikes)

### ISSUE THREAD

**Issue by darderik** [kayler-renslow/arma-intellij-plugin#22]
### Plugin Version

1.0.5 
### Summary

High CPU usage on specific files,and Intellij Crash
### Detail

Opening specific files (Like [this](https://raw.githubusercontent.com/ArmaLife/Framework/master/life_client/core/functions/fn_handleItem.sqf) one cause a crash,no logs.

![screenshot 2](https://cloud.githubusercontent.com/assets/14088415/17364260/7b238728-597f-11e6-88d8-1c7d64f84058.png)
IntelliJ is trying to loading for a few seconds,then it crashes.

**Comment by kayler-renslow** [comment]
I'm currently investigating this issue. I have a suspicion it's with case statements. Could you open up that file in notepad and let me know if you have a case statement in the file? Thanks.

**Comment by darderik** [comment]
Yes, I can confirm. There is a large case statement.

**Comment by kayler-renslow** [comment]
it definitely appears to be the case statement. I disabled it and a file with a large case statement opens fine. When enabling the case statement again, the large file freezes Intellij. This makes no sense...

**Comment by kayler-renslow** [comment]
I seem to have fixed the issue.

**Comment by kayler-renslow** [comment]
this is now fixed in version 1.0.5_1, which is available on the releases page.
