### ISSUE TITLE
Analyzing

### ISSUE THREAD

**Issue by darderik** [kayler-renslow/arma-intellij-plugin#23]
### Plugin Version

1.0.5_1
(Sorry for this... D:)
### Summary

The analyze feature could cause a freeze
### Detail

So,sometimes using the analyze>Inspect Code feature for checking syntax,could result in a freeze of IntelliJ,similiar to  the previous issue about loading large case statements file.

**Comment by kayler-renslow** [comment]
This has been fixed in 1.0.5_2. However, the inspections are really slow. I would recommend not doing the analyze feature on the whole project.
