### ISSUE TITLE
undefined-var highlighting has wrong positioning

### ISSUE THREAD

**Issue by BangL** [kayler-renslow/arma-intellij-plugin#24]
v1.0.5_1

as soon as i start using the "params" command, the highlighting indexes are getting shifted or something like that.

EDIT:
...the highlighting of unused params, to be more precise.

**Comment by BangL** [comment]
...the highlighting of unused params, to be more precise.

**Comment by kayler-renslow** [comment]
This is not useful information. Can you give me code to reproduce the issue?

**Comment by BangL** [comment]
nevermind, you already fixed this in 1.0.5_2 by using `getNonQuoteRangeRelativeToElement` instead of `getNonQuoteRangeRelativeToFile`. That was what i meant. sorry for my bad explanation. ;)

**Comment by BangL** [comment]
similar position-shifting of the highlighting still seem to happen in other cases, like "variable already declared private". version: 1.0.5_2

**Comment by kayler-renslow** [comment]
I can't fix this if you don't provide me an example of what's broken.

**Comment by BangL** [comment]
`
private _alreadyDeclared = "hello";
private _alreadyDeclared = "world"; // broken: highlighting shifted
private ["_alreadyDeclared"]; // This is making it even worse

private ["_alreadyDeclared2"]; // This is okay though
private ["_alreadyDeclared2"];

private _alreadyDeclared2 = "heya";
// the last line actually breaks it as well, but it shifts out of range - so you cant see it.

// But if you add more text like...
// blablablabla
// ... here it is.
`
http://250kb.de/u/160815/p/52JnuZcEkyym.png

**Comment by kayler-renslow** [comment]
fixed for 1.0.6
