### ISSUE TITLE
Crash with binarized mission SQM

### ISSUE THREAD

**Issue by SpazeGranade** [kayler-renslow/arma-intellij-plugin#25]
### Plugin Version

1.0.5_1
### Summary

Complete IDE crash with binarized mission.sqm
### Detail

If you have a binarized mission SQM in your project the IDE crashes.
Removing the mission file solves the problem.

Would be nice to just ignore binarized mission files.

**Comment by kayler-renslow** [comment]
I didn't realize that SQM mission files were converted into binary files until recently. These used to be header files. This would very much explain a crash I've been getting lately! THANK YOU FOR THIS SUBMISSION. :D

**Comment by kayler-renslow** [comment]
This has been fixed in 1.0.5_2. SQM files are now completely ignored.
