### ISSUE TITLE
for-var support

### ISSUE THREAD

**Issue by BangL** [kayler-renslow/arma-intellij-plugin#26]
v1.0.5_2

the for-var method does not handle the defined var as defined. ("_i" stais undefined)
the for-forspec method works fine though.

more info about what i mean by "for-var" and "for-forspec" here: https://community.bistudio.com/wiki/for

Example:
`
for "_i" from 0 to 2 do {
    hint str _i;
};
`

**Comment by BangL** [comment]
keep up the good work, you're close to bug free (already having a hard time searching for them)

**Comment by kayler-renslow** [comment]
fixed for 1.0.6
