### ISSUE TITLE
switch-do with multi-cases

### ISSUE THREAD

**Issue by BangL** [kayler-renslow/arma-intellij-plugin#28]
### Plugin Version

1.0.5_2
### Summary

switch-do with multi-cases
### Detail

code example:

`switch (_condition) do {
    case "string1";
    case "string2": { hint "string1 or string2" };
    default { hint "default" };
};`

the part`case "string1";` is falsly marked as syntax error. (at `;`) see example 1.2 and 4 here: https://community.bistudio.com/wiki/switch_do

**Comment by kayler-renslow** [comment]
fixed for 1.0.6
