### ISSUE TITLE
Non capital variable

### ISSUE THREAD

**Issue by Windmolders** [kayler-renslow/arma-intellij-plugin#3]
I noticed that functions are case sensitive:

But i know that they also work without cases what results in a syntax error for the plugin: eg

```
removebackpack player;
removeBackpack player;
```

The first one gives a error in the editor but works ingame to

Not sure if people want this or not. Open for debate ^.^

**Comment by kayler-renslow** [comment]
Commands are required to be camelCase. Even if it works in Arma, it will stay camel case.

**Comment by kayler-renslow** [comment]
In case you are wondering why, the lexer has to match close to 2,000 commands. If I were to allow commands to not be camel case, that is ~2,000 more rules. Besides the absolute useless amount of extra rules, it is harder to read commands that are not camel case in the SQF code than camel case ones.

**Comment by Windmolders** [comment]
@kayler-renslow No worries. I understand. Appreciate the work and plugin.

Good explanation to. Makes 100% sense.
