### ISSUE TITLE
#inlcude from rootdir

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#34]
plugin version 1.0.6

Error Message: "There is a syntax error."
# include "..\@tn.server\config.hpp"

. or ..  causes the false positive.

**Comment by kayler-renslow** [comment]
It shows the syntax error when the file doesn't exist. I marked this as a bug earlier, but I was derping and the file was in the wrong project. Everything appears to be working as intended.

**Comment by Ragebone** [comment]
Sorry, i can't remember what the heck went on. You are  right, problem solved. Thank you very much!
