### ISSUE TITLE
if not statement missing syntax

### ISSUE THREAD

**Issue by Windmolders** [kayler-renslow/arma-intellij-plugin#4]
The following code is shown as wrong but is actually correct: ( Line 1 ) 

``` sqf
if !(isServer) exitWith
{
    for "_i" from 0 to 99 do
    {
        diag_log "[ZCP]: Not a server";
    };
};
```

**Comment by kayler-renslow** [comment]
Although that works, `if 3 > 0 then {...};` doesn't. The grammar should be correct in all cases and not be ambiguous. With that said, all conditions must be inside "( )"

**Comment by kayler-renslow** [comment]
I rewrote the grammar for the next release and the code you posted will work now. However, I recommend avoiding writing conditionals that way because

```
if 0>3 exitWith
{
    for "_i" from 0 to 99 do
    {
        diag_log "[ZCP]: Not a server";
    };
};
```

will succeed in the grammar currently, but will fail in Arma since they (appear) to not evaluate expressions on an AST.
