### ISSUE TITLE
Multiple Addons in @Folder

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#52]
### Plugin Version
Future, looked at the last commit on your rewrite branch.
https://github.com/kayler-renslow/arma-intellij-plugin/commit/a8de9ba96187fcfa88393c760623cc7bb638d036
### Summary
Some @Mods contain multiple pbo addons. 
### Detail
Some parts of the last commit on your rewrite branch looked like you have set it up like one description.ext or config.cpp per module, but that will probably backfire in the said case.

I probably am wrong, and you probably did build it with multiple pbos in mind, but my understanding of what you committed isn't great enough that i could be sure of any of that, so i better embarrass myself and write this issue, instead of later running into this problem.

By the way, i looked at it hoping to get an understanding of what's going on that i can collaborate and contribute, once my current project A3XP is done and i was very happy to see that you are implementing real mod support!

**Comment by kayler-renslow** [comment]
I'm trying to get it to work for one config file first.

**Comment by kayler-renslow** [comment]
This was implemented in https://github.com/kayler-renslow/arma-intellij-plugin/commit/d586e0ae3f28adc4b800abd2188db103e8be80a3
