### ISSUE TITLE
"Not" keyword seems unknown to the plugin

### ISSUE THREAD

**Issue by kju** [kayler-renslow/arma-intellij-plugin#55]
see https://i.imgur.com/ddQSUsy.jpg

**Comment by kayler-renslow** [comment]
Weird. The not command is requiring a number rather than a boolean....

**Comment by kayler-renslow** [comment]
Interesting. The Bohemia Interactive Wiki also has the syntax listed as not NUMBER rather than not BOOLEAN

https://community.bistudio.com/wiki/not

**Comment by kayler-renslow** [comment]
fix is available in 2.0.0-pre2
