### ISSUE TITLE
diag commands not yet supported?

### ISSUE THREAD

**Issue by kju** [kayler-renslow/arma-intellij-plugin#61]
ref: https://i.imgur.com/cdVyM83.jpg

all:
https://community.bistudio.com/wiki/Arma_3_Diagnostics_Exe
https://community.bistudio.com/wiki/Category:Scripting_Commands_Arma_3

**Comment by kayler-renslow** [comment]
All of the diag commands should be supported. It looks like the error is actually with format command, but it is misreporting the error. Currently, I have format command to require a 2 length array. In this code sample you provided, you only have a 1 length array.

**Comment by kayler-renslow** [comment]
Fixed by making the format command require only a 1 length array

**Comment by kayler-renslow** [comment]
fix is available in 2.0.0-pre2
