### ISSUE TITLE
setPos with 2d position seems not recognized

### ISSUE THREAD

**Issue by kju** [kayler-renslow/arma-intellij-plugin#62]
### Plugin Version
v2 pre4

### Summary
`player setPos [0,0]`
see: https://i.imgur.com/CkaajlH.jpg

### Detail
Ref: https://community.bistudio.com/wiki/setPos

**Comment by kayler-renslow** [comment]
Fixed in https://github.com/kayler-renslow/arma-intellij-plugin/commit/a73eb24a9c8d10764fe1f26ce9f68f3bfc8a1cd7

Forgot to mark the last parameter of BaseType.POSITION as optional.

**Comment by kayler-renslow** [comment]
fixed in 2.0.0-pre5
