### ISSUE TITLE
Feature: VSCode like commands

### ISSUE THREAD

**Issue by jcbjoe** [kayler-renslow/arma-intellij-plugin#65]
### Plugin Version
1.0.9
### Summary
Would it be possible to make the cntrl hover look a little like the 
### Detail
Would it be possible to make the cntrl hover look a little like the one in visual studio code's arma plugin? Will post a link to what it looks like.
https://i.gyazo.com/6bffe5d8455e1ed8b566da32a510b075.png

**Comment by kayler-renslow** [comment]
I don't think I can change this functionality. There is a way to view the documentation for the commands by pushing Ctrl+Q with your cursor on a command. You can change the keybind for that (it's called "Quick Documentation" in keybinds).
