### ISSUE TITLE
while  loop,  "empty Element parsed in 'loop_while_2' at ofset 849

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#7]
code:

```
while {(count _queryResult) == 0 } do {
        // ask for his userID
        _query = format["checkUser:%1",_steamID];
        _queryResult = [_query,2,false] call Server_fnc_callDB;
    };
```

its the   closing bracket of the argument  == 0 **}**   that is marked as mistake with the message that is the topic.
Besides that, adding commands into the argument marks the semicolon as a syntax error.

`While { ... ; ... }do { ... };`

https://community.bistudio.com/wiki/while

**Comment by kayler-renslow** [comment]
fixed for next release

**Comment by Ragebone** [comment]
thank you very much !
