### ISSUE TITLE
Variable unused

### ISSUE THREAD

**Issue by Ragebone** [kayler-renslow/arma-intellij-plugin#8]
nothing major but its kind of wierd.
Version 1.0.3

[_veh,_lights,_time] spawn {
    // initiate the flipflop.
    private["_boolean"];
    _vehicle = _this select 0;
    _lights = _this select 1;
    _boolean = true; // <------- marks _boolean as not used.
    {
        _x setCollisionLight _boolean;     // but it is used.
        _boolean = !_boolean;
    }forEach _vehicle;

**Comment by kayler-renslow** [comment]
Interesting. This has somehow already been fixed for the next version when I re-implemented almost the entire grammar weeks ago for 1.0.4.
