### ISSUE TITLE
in is not supported as condition

### ISSUE THREAD

**Issue by Clon1998** [kayler-renslow/arma-intellij-plugin#9]
see title :P

**Comment by kayler-renslow** [comment]
Are you talking about this?:https://github.com/kayler-renslow/arma-intellij-plugin/issues/4

**Comment by Clon1998** [comment]
Well i have to admit the information i gave you sux.
I mean a "in" condition.
Example:
`if ("lol" in ["lol","LMAO","stfu"]) then {
hint "Yay lol is in the array";
};`

**Comment by kayler-renslow** [comment]
This appears to be fixed for next version (1.0.4)
